# Generated by Django 3.0.4 on 2020-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', '管理员'), ('worker', '操作员')], default='操作员', max_length=32),
        ),
    ]
